.MODEL SMALL
.STACK 100H
.DATA                   
    
    INPUT_ERROR DB 0DH,0AH,0DH,0AH,'!!!...WRONG INPUT...!!!',24H
    NUMBER_1_INPUT_MSG DB 0DH,0AH,'PLEASE INPUT THE FIRST NUMBER: $'
    NUMBER_2_INPUT_MSG DB 0DH,0AH,'PLEASE INPUT THE SECOND NUMBER: $'   
    OPTION_DIVISION_RESULT DB 0DH,0AH,0DH,0AH,'DIVISION RESULT OF THIS TWO NUMBER IS: $'
    OPTION_DIVISION_REMINDER DB 0DH,0AH,0DH,0AH,'DIVISION REMINDER OF THIS TWO NUMBER IS: $'
    EXIT_CONFIRMATION_MSG DB 0DH,0AH,0DH,0AH,'WOULD YOU LIKE TO EXIT THEN PRESS "Y": $'
    NUMBER_1 DW '?'
    NUMBER_2 DW '?'
    RESULT DW '?'
    DIVISION_RESULT DB '?'
    DIVISION_REMINDER DB '?'
    DIVISION_FLAG DB '?'
    ENTER DB 0DH,0AH,24H
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS,AX
        
INPUT_SEGMENT:
    CALL INPUT    
MENU_SEGMENT:
    CALL DIVISION    
DECISION_SEGMENT:
                    
    CALL DIVISION
OUTPUT_SEGMENT:
    CALL OUTPUT         
EXIT_SEGMENT:
    MOV AH,9
    LEA DX,EXIT_CONFIRMATION_MSG
    INT 21H
    MOV AH,1
    INT 21H
    CMP AL,59H
        JNE INPUT_SEGMENT
    MOV AH,4CH
    INT 21H         
    MAIN ENDP
INPUT PROC    
        JMP NUMBER_1_INPUT_SEGMENT
NUMBER_1_INPUT_ERROR_SEGMENT:
    MOV AH,9
    LEA DX,INPUT_ERROR
    INT 21H
    MOV AH,9
    LEA DX,ENTER
    INT 21H
NUMBER_1_INPUT_SEGMENT:
    MOV AH,9
    LEA DX,NUMBER_1_INPUT_MSG
    INT 21H
    MOV CX,5
    XOR BX,BX
NUMBER_1_INPUT_LOOP:        
    MOV AH,1
    INT 21H
    CMP AL,0DH
        JE NUMBER_2_INPUT_SEGMENT 
    CMP AL, 30H
        JL NUMBER_1_INPUT_ERROR_SEGMENT           
    CMP AL, 39H
        JG NUMBER_1_INPUT_ERROR_SEGMENT     
    MOV AH,0H    
    SUB AL,30H    
    PUSH AX
    MOV AX, 0AH
    MUL BX
    POP BX
    ADD BX,AX 
        LOOP NUMBER_1_INPUT_LOOP
    JMP NUMBER_2_INPUT_SEGMENT                      
NUMBER_2_INPUT_ERROR_SEGMENT:
    MOV AH,9
    LEA DX,INPUT_ERROR
    INT 21H
    MOV AH,9
    LEA DX,ENTER
    INT 21H         
NUMBER_2_INPUT_SEGMENT:   
    MOV AH,9
    LEA DX,NUMBER_2_INPUT_MSG
    INT 21H
    MOV CX,5
    XOR DX,DX
NUMBER_2_INPUT_LOOP:       
    MOV AH,1
    INT 21H
    CMP AL,0DH
        JE DATA_STORE_SEGMENT
    CMP AL, 30H
        JL NUMBER_2_INPUT_ERROR_SEGMENT           
    CMP AL, 39H
        JG NUMBER_2_INPUT_ERROR_SEGMENT    
    MOV AH,0H    
    SUB AL,30H    
    PUSH AX
    MOV AX, 0AH
    MUL DX
    POP DX
    ADD DX,AX
        LOOP NUMBER_2_INPUT_LOOP
DATA_STORE_SEGMENT:
    MOV NUMBER_1, BX
    MOV NUMBER_2, DX
        JMP MENU_SEGMENT
    INPUT ENDP

DIVISION PROC
    XOR AX,AX
    XOR BX,BX 
    MOV AX,NUMBER_1
    MOV BX,NUMBER_2
    CMP AX,BX
        JL REVERSE_DIVISION
    DIV BL
    MOV DIVISION_RESULT, AL
    MOV DIVISION_REMINDER, AH
    MOV CL, 1
    MOV DIVISION_FLAG, CL
        JMP OUTPUT_SEGMENT
REVERSE_DIVISION:
    MOV AH,9
    LEA DX,INPUT_ERROR
    INT 21H 
        JMP EXIT_SEGMENT                
    DIVISION ENDP
PROC OUTPUT
    MOV CL, DIVISION_FLAG
    OR CL,CL
        JNE DIVISION_MODIFY_RESULT
    MOV AX,RESULT
VALUE_PUSH:        
    PUSH AX
    POP AX
    XOR CX,CX
    XOR DX,DX
    MOV BX,10D   
DECIMAL_CONVERT_SEGMENT:
    DIV BX
    PUSH DX
    XOR DX,DX
    INC CX
    OR AX,AX
        JNE DECIMAL_CONVERT_SEGMENT
RESULT_PRINT_SEGMENT:
    POP DX
    ADD DL,30H
    MOV AH,02
    INT 21H
        LOOP RESULT_PRINT_SEGMENT
     MOV CL,DIVISION_FLAG
    CMP CL,2
        JE DIVISION_MODIFY_REMINDER           
    JMP EXIT_SEGMENT
DIVISION_MODIFY_RESULT:
    MOV AH,9
    LEA DX,OPTION_DIVISION_RESULT
    INT 21H
    MOV AL,DIVISION_RESULT
    XOR AH,AH
    MOV CL,2
    MOV DIVISION_FLAG,CL
        JMP VALUE_PUSH
DIVISION_MODIFY_REMINDER:
    MOV CL,1
    MOV DIVISION_FLAG,CL              
    MOV AH,9
    LEA DX,OPTION_DIVISION_REMINDER
    INT 21H 
    MOV AL,DIVISION_REMINDER
    XOR AH,AH
        JMP VALUE_PUSH
    OUTPUT ENDP
ENDP MAIN    